# Generated by Django 4.2.7 on 2023-11-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=100)),
                ("deadline", models.DateTimeField()),
                ("delete_flg", models.IntegerField(default=0)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
